site:
  about:
    siteName: 'Après la dépression'
    subtitle: 'Mettre à profit la période après la dépression pour ne pas y retomber'
    siteDescription: 'Livre en cours d''écriture'
    avatar: '/assets/media/logo.jpg'

theme:
  social:
    facebook: 'jmfayard'
    github: 'jmfayard'
    other:
      - label: 'linkedin'
        link: 'https://www.linkedin.com/in/jeanmichelfayard/'
        icon: 'fa-tag'
  menu:
    - type: 'page'
      title: 'Home'
      url: '/'
    - type: "wikiSections"
    - type: "pageSubtree"
      itemId: 'wiki'

  #    - type: 'taxonomy'
#      taxonomyType: 'categories'
#      includeTerms: true
#      termsAtRoot: true
#    - type: 'page'
#      title: 'About'
#      itemId: 'Author One'
#    - type: "pages"
#      atRoot: true

#    - type: recentPosts
#      limit: 3
#      category: gallery
#      noWrapper: true
#      template:
#        - 'includes/postPreview_mini'
#    - type: recentPosts
#      limit: 5
#      category: personal
#      noWrapper: true
#      template:
#        - 'includes/postPreview_list'
  extraCss:
    #- 'assets/css/asciidoctor.css'
    - 'assets/css/pygments.scss'
  extraJs:
    - 'assets/js/extraJs.js'

services:
  generators:
    externalIndices:
      - 'https://orchid.netlify.com/meta/all.index.json'


sitemap:
  useRobots: false
  useSitemaps: true

