permalink: ':category/:slug'
categories:
  - key: 'concepts'
    title: 'Concepts clés'
  - key: 'questions-existentielles'
    title: 'Questions existentielles'
authors:
  - name: 'Jean-Michel Fayard'
    avatar: 'assets/images/profile-picture-jmfayard.jpg'
    email: 'jmfayard+apresladepression@gmail.com'
postPages:
  author: 'Jean-Michel Fayard'
  layout: single
  components:
    - type: pageContent
    - type: taxonomy
      taxonomyType: tags
    - type: taxonomy
      taxonomyType: categories
